---

- hosts: all
  become: true

  vars_files:
  - my_vars.yml

  tasks:

    - name: Delete Old Cert Zip
      file:
        path: "cert.zip"
        state: absent
  
    - name: Delete Old Response File
      file:
        path: "Certificates.json"
        state: absent

#### When are we? #####################################################################################
                
    - name: Register Current Hour as End Time
      set_fact:
        end_time: "{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
   
    - name: Munge Epoch Time Minus 16 Minutes for Start Time
      set_fact:
        start_time: "{{ '%H:%M' | strftime( ( ansible_date_time.epoch | int ) - ( 60 * 16 )  ) }}"

    - name: Register Current Date
      set_fact:
        date: "{{ ansible_date_time.date }}"

#### Qualtrics All The Things! ##########################################################################
                
    - name: Create Qualtrics Response Export
      shell: |
        curl -X POST -H 'X-API-TOKEN: {{ cert_api_token }}' -H 'Content-Type: application/json' -d '{ 
        "surveyId": "{{ cert_survey_id }}",
        "format": "json",
        "startDate": "{{ date }}T{{ start_time }}:00-05:00",
        "endDate": "{{ date }}T{{ end_time }}:00-05:00",
        "useLabels": true
        }' 'https://ousurvey.qualtrics.com/API/v3/responseexports'
      register: cert_export

    - name: Register Qualtrics Request ID
      set_fact:
        cert_request_id: '{{ (cert_export.stdout | from_json).result.id }}'

    - name: Check Status of Qualtrics Response Export
      shell: |
        curl -H 'X-API-TOKEN: {{ cert_api_token }}' 'https://ousurvey.qualtrics.com/API/v3/responseexports/{{ cert_request_id }}'
      register: qualtrics_progress
      until: qualtrics_progress.stdout.find("100.0") != -1
      retries: 5
      delay: 5

    - name: Download Qualtrics Response Export
      shell: |
        curl -X GET -H "Content-Type: application/json" -H "X-API-TOKEN: {{ cert_api_token }}" "https://ousurvey.qualtrics.com/API/v3/responseexports/{{ cert_request_id }}/file" -o cert.zip
      ignore_errors: True

    - name: Unzip Response File
      unarchive:
        src: cert.zip
        dest: .
      ignore_errors: True

    - name: Import JSON as Variables
      set_fact:      
        cert_vars: "{{ lookup('file','Certificates.json') | from_json }}"
      ignore_errors: True

    - name: Check to see number of Certificates
      set_fact:
        cert_count: '{{ item.certcount }}'
      with_items: '{{ cert_vars.responses }}'

###### Certificate 01 ##########################################################################

    - name: Ensure Directories Exist for 1st Certificate
      file: 
        path: '{{ cert_file_path }}/{{ item.name01 }}'
        state: directory
      when: cert_count | int >= 1
      with_items: '{{ cert_vars.responses }}'
    
    - name: Download 1st Certificate and Place In Folder
      get_url:
        url: "{{ item.pdf01_FILE_ID }}"
        dest: "{{ cert_file_path }}/{{ item.name01 }}/{{ item.name01 }} {{ item.expire01 }}.pdf"
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 1
      ignore_errors: yes
    
    - name: Rename 1st WC Cert
      command: mv -f "{{ cert_file_path }}/{{ item.name01 }}/{{ item.name01 }} {{ item.expire01 }}.pdf" "{{ cert_file_path }}/{{item.name01 }}/{{ item.name01 }} {{ item.expire01 }} WC {{ item.compexp01 }}.pdf"
      when: item.comp01 == "Yes"
      with_items: "{{ cert_vars.responses }}"
      ignore_errors: True
      delegate_to: localhost
          
    - name: Notify Slack of 1st File Completion
      slack:
        token: '{{ slack_token }}'
        msg: The COI for '{{ item.name01 }}' has been filed.
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 1
          
###### Certificate 02 ##########################################################################

    - name: Ensure Directories Exist for 2nd Certificate
      file: 
        path: '{{ cert_file_path }}/{{ item.name02 }}'
        state: directory
      when: cert_count | int >= 2
      with_items: '{{ cert_vars.responses }}'
    
    - name: Download 2nd Certificate and Place In Folder
      get_url:
        url: "{{ item.pdf02_FILE_ID }}"
        dest: "{{ cert_file_path }}/{{ item.name02 }}/{{ item.name02 }} {{ item.expire02 }}.pdf"
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 2
      ignore_errors: yes
    
    - name: Rename 2nd WC Cert
      command: mv -f "{{ cert_file_path }}/{{ item.name02 }}/{{ item.name02 }} {{ item.expire02 }}.pdf" "{{ cert_file_path }}/{{item.name02 }}/{{ item.name02 }} {{ item.expire02 }} WC {{ item.compexp02 }}.pdf"
      when: item.comp02 == "Yes"
      with_items: "{{ cert_vars.responses }}"
      ignore_errors: True
      delegate_to: localhost
          
    - name: Notify Slack of 2nd File Completion
      slack:
        token: '{{ slack_token }}'
        msg: The COI for '{{ item.name02 }}' has been filed.
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 2

###### Certificate 03 ##########################################################################

    - name: Ensure Directories Exist for 3rd Certificate
      file: 
        path: '{{ cert_file_path }}/{{ item.name03 }}'
        state: directory
      when: cert_count | int >= 3
      with_items: '{{ cert_vars.responses }}'
    
    - name: Download 3rd Certificate and Place In Folder
      get_url:
        url: "{{ item.pdf03_FILE_ID }}"
        dest: "{{ cert_file_path }}/{{ item.name03 }}/{{ item.name03 }} {{ item.expire03 }}.pdf"
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 3
      ignore_errors: yes
    
    - name: Rename 3rd WC Cert
      command: mv -f "{{ cert_file_path }}/{{ item.name03 }}/{{ item.name03 }} {{ item.expire03 }}.pdf" "{{ cert_file_path }}/{{item.name03 }}/{{ item.name03 }} {{ item.expire03 }} WC {{ item.compexp03 }}.pdf"
      when: item.comp03 == "Yes"
      with_items: "{{ cert_vars.responses }}"
      ignore_errors: True
      delegate_to: localhost
          
    - name: Notify Slack of 3rd File Completion
      slack:
        token: '{{ slack_token }}'
        msg: The COI for '{{ item.name03 }}' has been filed.
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 3

###### Certificate 04 ##########################################################################

    - name: Ensure Directories Exist for 4th Certificate
      file: 
        path: '{{ cert_file_path }}/{{ item.name04 }}'
        state: directory
      when: cert_count | int >= 4
      with_items: '{{ cert_vars.responses }}'
    
    - name: Download 4th Certificate and Place In Folder
      get_url:
        url: "{{ item.pdf04_FILE_ID }}"
        dest: "{{ cert_file_path }}/{{ item.name04 }}/{{ item.name04 }} {{ item.expire04 }}.pdf"
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 4
      ignore_errors: yes
    
    - name: Rename 4th WC Cert
      command: mv -f "{{ cert_file_path }}/{{ item.name04 }}/{{ item.name04 }} {{ item.expire04 }}.pdf" "{{ cert_file_path }}/{{item.name04 }}/{{ item.name04 }} {{ item.expire04 }} WC {{ item.compexp04 }}.pdf"
      when: item.comp04 == "Yes"
      with_items: "{{ cert_vars.responses }}"
      ignore_errors: True
      delegate_to: localhost
          
    - name: Notify Slack of 4th File Completion
      slack:
        token: '{{ slack_token }}'
        msg: The COI for '{{ item.name04 }}' has been filed.
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 4

###### Certificate 05 ##########################################################################

    - name: Ensure Directories Exist for 5th Certificate
      file: 
        path: '{{ cert_file_path }}/{{ item.name05 }}'
        state: directory
      when: cert_count | int >= 5
      with_items: '{{ cert_vars.responses }}'
    
    - name: Download 5th Certificate and Place In Folder
      get_url:
        url: "{{ item.pdf05_FILE_ID }}"
        dest: "{{ cert_file_path }}/{{ item.name05 }}/{{ item.name05 }} {{ item.expire05 }}.pdf"
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 5
      ignore_errors: yes
    
    - name: Rename 5th WC Cert
      command: mv -f "{{ cert_file_path }}/{{ item.name05 }}/{{ item.name05 }} {{ item.expire05 }}.pdf" "{{ cert_file_path }}/{{item.name05 }}/{{ item.name05 }} {{ item.expire05 }} WC {{ item.compexp05 }}.pdf"
      when: item.comp05 == "Yes"
      with_items: "{{ cert_vars.responses }}"
      ignore_errors: True
      delegate_to: localhost
          
    - name: Notify Slack of 5th File Completion
      slack:
        token: '{{ slack_token }}'
        msg: The COI for '{{ item.name05 }}' has been filed.
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 5

###### Certificate 06 ##########################################################################

    - name: Ensure Directories Exist for 6th Certificate
      file: 
        path: '{{ cert_file_path }}/{{ item.name06 }}'
        state: directory
      when: cert_count | int >= 6
      with_items: '{{ cert_vars.responses }}'
    
    - name: Download 6th Certificate and Place In Folder
      get_url:
        url: "{{ item.pdf06_FILE_ID }}"
        dest: "{{ cert_file_path }}/{{ item.name06 }}/{{ item.name06 }} {{ item.expire06 }}.pdf"
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 6
      ignore_errors: yes
    
    - name: Rename 6th WC Cert
      command: mv -f "{{ cert_file_path }}/{{ item.name06 }}/{{ item.name06 }} {{ item.expire06 }}.pdf" "{{ cert_file_path }}/{{item.name06 }}/{{ item.name06 }} {{ item.expire06 }} WC {{ item.compexp06 }}.pdf"
      when: item.comp06 == "Yes"
      with_items: "{{ cert_vars.responses }}"
      ignore_errors: True
      delegate_to: localhost
          
    - name: Notify Slack of 6th File Completion
      slack:
        token: '{{ slack_token }}'
        msg: The COI for '{{ item.name06 }}' has been filed.
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 6

###### Certificate 07 ##########################################################################

    - name: Ensure Directories Exist for 7th Certificate
      file: 
        path: '{{ cert_file_path }}/{{ item.name07 }}'
        state: directory
      when: cert_count | int >= 7
      with_items: '{{ cert_vars.responses }}'
    
    - name: Download 7th Certificate and Place In Folder
      get_url:
        url: "{{ item.pdf07_FILE_ID }}"
        dest: "{{ cert_file_path }}/{{ item.name07 }}/{{ item.name07 }} {{ item.expire07 }}.pdf"
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 7
      ignore_errors: yes
    
    - name: Rename 7th WC Cert
      command: mv -f "{{ cert_file_path }}/{{ item.name07 }}/{{ item.name07 }} {{ item.expire07 }}.pdf" "{{ cert_file_path }}/{{item.name07 }}/{{ item.name07 }} {{ item.expire07 }} WC {{ item.compexp07 }}.pdf"
      when: item.comp07 == "Yes"
      with_items: "{{ cert_vars.responses }}"
      ignore_errors: True
      delegate_to: localhost
          
    - name: Notify Slack of 7th File Completion
      slack:
        token: '{{ slack_token }}'
        msg: The COI for '{{ item.name07 }}' has been filed.
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 7

###### Certificate 08 ##########################################################################

    - name: Ensure Directories Exist for 8th Certificate
      file: 
        path: '{{ cert_file_path }}/{{ item.name08 }}'
        state: directory
      when: cert_count | int >= 8
      with_items: '{{ cert_vars.responses }}'
    
    - name: Download 8th Certificate and Place In Folder
      get_url:
        url: "{{ item.pdf08_FILE_ID }}"
        dest: "{{ cert_file_path }}/{{ item.name08 }}/{{ item.name08 }} {{ item.expire08 }}.pdf"
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 8
      ignore_errors: yes
    
    - name: Rename 8th WC Cert
      command: mv -f "{{ cert_file_path }}/{{ item.name08 }}/{{ item.name08 }} {{ item.expire08 }}.pdf" "{{ cert_file_path }}/{{item.name08 }}/{{ item.name08 }} {{ item.expire08 }} WC {{ item.compexp08 }}.pdf"
      when: item.comp08 == "Yes"
      with_items: "{{ cert_vars.responses }}"
      ignore_errors: True
      delegate_to: localhost
          
    - name: Notify Slack of 8th File Completion
      slack:
        token: '{{ slack_token }}'
        msg: The COI for '{{ item.name08 }}' has been filed.
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 8

###### Certificate 09 ##########################################################################

    - name: Ensure Directories Exist for 9th Certificate
      file: 
        path: '{{ cert_file_path }}/{{ item.name09 }}'
        state: directory
      when: cert_count | int >= 9
      with_items: '{{ cert_vars.responses }}'
    
    - name: Download 9th Certificate and Place In Folder
      get_url:
        url: "{{ item.pdf09_FILE_ID }}"
        dest: "{{ cert_file_path }}/{{ item.name09 }}/{{ item.name09 }} {{ item.expire09 }}.pdf"
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 9
      ignore_errors: yes
    
    - name: Rename 9th WC Cert
      command: mv -f "{{ cert_file_path }}/{{ item.name09 }}/{{ item.name09 }} {{ item.expire09 }}.pdf" "{{ cert_file_path }}/{{item.name09 }}/{{ item.name09 }} {{ item.expire09 }} WC {{ item.compexp09 }}.pdf"
      when: item.comp09 == "Yes"
      with_items: "{{ cert_vars.responses }}"
      ignore_errors: True
      delegate_to: localhost
          
    - name: Notify Slack of 9th File Completion
      slack:
        token: '{{ slack_token }}'
        msg: The COI for '{{ item.name09 }}' has been filed.
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 9

###### Certificate 10 ##########################################################################

    - name: Ensure Directories Exist for 10th Certificate
      file: 
        path: '{{ cert_file_path }}/{{ item.name10 }}'
        state: directory
      when: cert_count | int >= 10
      with_items: '{{ cert_vars.responses }}'
    
    - name: Download 10th Certificate and Place In Folder
      get_url:
        url: "{{ item.pdf10_FILE_ID }}"
        dest: "{{ cert_file_path }}/{{ item.name10 }}/{{ item.name10 }} {{ item.expire10 }}.pdf"
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 10
      ignore_errors: yes
    
    - name: Rename 10th WC Cert
      command: mv -f "{{ cert_file_path }}/{{ item.name10 }}/{{ item.name10 }} {{ item.expire10 }}.pdf" "{{ cert_file_path }}/{{item.name10 }}/{{ item.name10 }} {{ item.expire10 }} WC {{ item.compexp10 }}.pdf"
      when: item.comp10 == "Yes"
      with_items: "{{ cert_vars.responses }}"
      ignore_errors: True
      delegate_to: localhost
          
    - name: Notify Slack of 10th File Completion
      slack:
        token: '{{ slack_token }}'
        msg: The COI for '{{ item.name10 }}' has been filed.
      with_items: "{{ cert_vars.responses }}"
      when: cert_count | int >= 10


