---

- hosts: all
  become: true

  vars_files:
  - my_vars.yml

  tasks:
    - name: Import JSON as Variables
      set_fact: 
        qualtrics_vars: "{{ lookup('file','Purchasing Solicitations.json') | from_json }}"
      ignore_errors: True

    - name: Debug 1 Time
      debug:
        msg: "This is {{ item.Q25 }}"
      with_items: '{{ qualtrics_vars.responses }}'

    - name: Ensure Directories Exist
      file: 
        path: '{{ cert_file_path }}/{{ item.Q26 }}'
        state: directory
      with_items: '{{ qualtrics_vars.responses }}'

