---

- hosts: all
  become: true

  vars_files:
  - my_vars.yml

  tasks:
    - name: Register Current Hour as End Time
      set_fact:
        end_time: "{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
    
    - name: Munge Epoch Time Minus 15 Minutes for Start Time
      set_fact:
        start_time: "{{ '%H:%M' | strftime( ( ansible_date_time.epoch | int ) - ( 60 * 30 )  ) }}"

    - name: Register Current Date
      set_fact:
        date: "{{ ansible_date_time.date }}"

    - name: Create Qualtrics Response Export
      shell: |
        curl -X POST -H 'X-API-TOKEN: {{ qualtrics_api_token }}' -H 'Content-Type: application/json' -d '{ 
        "surveyId": "{{ qualtrics_survey_id }}",
        "format": "json",
        "startDate": "{{ date }}T{{ start_time }}:00-05:00",
        "endDate": "{{ date }}T{{ end_time }}:00-05:00",
        "useLabels": true
        }' 'https://ousurvey.qualtrics.com/API/v3/responseexports'
      register: qualtrics_export

    - name: Register Qualtrics Request ID
      set_fact:
        qualtrics_request_id: '{{ (qualtrics_export.stdout | from_json).result.id }}'

    - name: Check Status of Qualtrics Response Export
      shell: |
        curl -H 'X-API-TOKEN: {{ qualtrics_api_token }}' 'https://ousurvey.qualtrics.com/API/v3/responseexports/{{ qualtrics_request_id }}'
      register: qualtrics_progress

    - name: Download Qualtrics Response Export
      shell: |
        curl -X GET -H "Content-Type: application/json" -H "X-API-TOKEN: {{ qualtrics_api_token }}" "https://ousurvey.qualtrics.com/API/v3/responseexports/{{ qualtrics_request_id }}/file" -o response.zip
      register: qualtrics_progress

    - name: Unzip Response File
      shell: |
        unzip response.zip

    - name: Import JSON
      set_fact:      
        qualtrics_vars: "{{ lookup('file','Purchasing Solicitations.json') | from_json }}"
      ignore_errors: True

    - name: Delete Old Response Zip
      file:
        path: "response.zip"
        state: absent
   
    - name: Delete Old Response File
      file:
        path: "Purchasing Solicitations.json"
        state: absent

    - name: Debug Qualtrics Vars
      debug:
        msg: "The Sol Number is '{{ item.Q1 }}' and the Title is '{{ item.Q2 }}'"
      with_items: '{{ qualtrics_vars.responses }}'




