---

- hosts: all
  become: true

  vars_files:
  - my_vars.yml

  tasks:

    - name: Delete Old Response Zip
      file:
        path: "sol.zip"
        state: absent
  
    - name: Delete Old Response File
      file:
        path: "Solicitations.json"
        state: absent

#### When are we? #####################################################################################

    - name: Register Current Hour as End Time
      set_fact:
        end_time: "{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
   
    - name: Munge Epoch Time Minus 11 Minutes for Start Time
      set_fact:
        start_time: "{{ '%H:%M' | strftime( ( ansible_date_time.epoch | int ) - ( 60 * 11 )  ) }}"

    - name: Register Current Date
      set_fact:
        date: "{{ ansible_date_time.date }}"

#### Qualtrics All The Things! #####################################################################################

    - name: Create Qualtrics Response Export
      shell: |
        curl -X POST -H 'X-API-TOKEN: {{ sol_api_token }}' -H 'Content-Type: application/json' -d '{ 
        "surveyId": "{{ sol_survey_id }}",
        "format": "json",
        "startDate": "{{ date }}T{{ start_time }}:00-05:00",
        "endDate": "{{ date }}T{{ end_time }}:00-05:00",
        "useLabels": true
        }' 'https://ousurvey.qualtrics.com/API/v3/responseexports'
      register: sol_export

    - name: Register Qualtrics Request ID
      set_fact:
        sol_request_id: '{{ (sol_export.stdout | from_json).result.id }}'

    - name: Check Status of Qualtrics Response Export
      shell: |
        curl -H 'X-API-TOKEN: {{ sol_api_token }}' 'https://ousurvey.qualtrics.com/API/v3/responseexports/{{ sol_request_id }}'
      register: qualtrics_progress
      until: qualtrics_progress.stdout.find("100.0") != -1
      retries: 5
      delay: 5

    - name: Check Status of Qualtrics Response Export
      shell: |
        curl -H 'X-API-TOKEN: {{ sol_api_token }}' 'https://ousurvey.qualtrics.com/API/v3/responseexports/{{ sol_request_id }}'
      register: sol_progress

    - name: Download Qualtrics Response Export
      shell: |
        curl -X GET -H "Content-Type: application/json" -H "X-API-TOKEN: {{ sol_api_token }}" "https://ousurvey.qualtrics.com/API/v3/responseexports/{{ sol_request_id }}/file" -o sol.zip
      ignore_errors: True

    - name: Unzip Response File
      unarchive:
        src: sol.zip
        dest: .
      ignore_errors: True

    - name: Import JSON as Variables
      set_fact:      
        sol_vars: "{{ lookup('file','Solicitations.json') | from_json }}"
      ignore_errors: True

#### Insert Solicitation #####################################################################################

    - name: Create Backup of HTML
      raw: cp "{{ solicitation_html_path }}" "{{ solicitation_backup_path }}/solicitations.{{ ansible_date_time.date }}.{{ ansible_date_time.hour }}.{{ ansible_date_time.minute }}.html"
          
    - name: Modify Solicitation HTML
      blockinfile:
        path: '{{ solicitation_html_path }}'
        marker: "<!-- {mark} {{ item.solclosedate }} {{ item.solclosetime }} {{ item.solnumber }}-->"
        content: |
          <tr id="data">
            <td id="data"><span id="title"><b><u>{{ item.solnumber }}</u></b><br><br>{{ item.soltitle }}<span><br><br></td>
            <td id="{{ item.solnumber }} Campus">{{ item.solcampus }}</td>
            <td id="{{ item.solnumber }} Buyer">{{ item.solbuyer }}<br> email: <a href="mailto:{{ item.solemail }}">{{ item.solemail }}</a></td>
            <td id="{{ item.solnumber }} Open">{{ item.solopen }}</td>
            <td id="{{ item.solnumber }} Close">{{ item.solclosedate }} at {{ item.solclosetime }} CT</td>
            <td id="{{ item.solnumber }} PDF">[ <a href="documents/{{ item.solnumber }}/{{ item.solpdf_FILE_NAME }}" target="_blank">{{ item.solnumber }}</a> ]<br><br></td>
            <td id="{{ item.solnumber }} attach">
            </td>
          </tr>
        state: present
        insertbefore: "end solicitations"
      when: item.soltype == "New"
      with_items: '{{ sol_vars.responses }}'
      register: modified
  
    - name: Create Solicitation Directories
      file:
        path: '{{ solicitation_doc_path }}/{{ item.solnumber }}'
        state: directory
        mode: '0755'
      with_items: '{{ sol_vars.responses }}'
  
    - name: Download Solicitation Files
      get_url:
        url: '{{ item.solpdf_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solpdf_FILE_NAME }}'
      when: item.solpdf_FILE_NAME
      with_items: '{{ sol_vars.responses }}'
      ignore_errors: True

#### Addendum #####################################################################################       

    - name: Check to see if there is an Addendum
      set_fact:
        addendum: '{{ item.soladd }}'
      with_items: '{{ sol_vars.responses }}'
  
    - name: Insert Addendum
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.soladdpdf_FILE_NAME }}" target="_blank">{{ item.soladdpdf_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: addendum
      ignore_errors: True
  
    - name: Download Addendum
      get_url:
        url: '{{ item.soladdpdf_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.soladdpdf_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: addendum

#### Attachment #####################################################################################
          
    - name: Check to see if there are Attachments
      set_fact:
        attachments: '{{ item.solatt }}'
      with_items: '{{ sol_vars.responses }}'
  
    - name: Check to see number of Attachments
      set_fact:
        attachment_count: '{{ item.solattcount }}'
      with_items: '{{ sol_vars.responses }}'
 
#### 1st Attachment #####################################################################################
 
    - name: Insert 1st Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.solatt01_FILE_NAME }}" target="_blank">{{ item.solatt01_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 1
      ignore_errors: True
  
    - name: Download 1st Attachment
      get_url:
        url: '{{ item.solatt01_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solatt01_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 1
      ignore_errors: True

#### 2nd Attachment #####################################################################################
 
    - name: Insert 2nd Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.solatt02_FILE_NAME }}" target="_blank">{{ item.solatt02_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 2
      ignore_errors: True
  
    - name: Download 2nd Attachment
      get_url:
        url: '{{ item.solatt02_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solatt02_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 2
      ignore_errors: True
          
#### 3rd Attachment #####################################################################################
 
    - name: Insert 3rd Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.solatt03_FILE_NAME }}" target="_blank">{{ item.solatt03_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 3
      ignore_errors: True
  
    - name: Download 3rd Attachment
      get_url:
        url: '{{ item.solatt03_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solatt03_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 3
      ignore_errors: True

#### 4th Attachment #####################################################################################
 
    - name: Insert 4th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.solatt04_FILE_NAME }}" target="_blank">{{ item.solatt04_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 4
      ignore_errors: True
  
    - name: Download 4th Attachment
      get_url:
        url: '{{ item.solatt04_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solatt04_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 4
      ignore_errors: True

#### 5th Attachment #####################################################################################
 
    - name: Insert 5th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.solatt04_FILE_NAME }}" target="_blank">{{ item.solatt04_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 4
      ignore_errors: True
  
    - name: Download 5th Attachment
      get_url:
        url: '{{ item.solatt05_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solatt05_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 5
      ignore_errors: True

#### 6th Attachment #####################################################################################
 
    - name: Insert 6th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.solatt06_FILE_NAME }}" target="_blank">{{ item.solatt06_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 6
      ignore_errors: True
  
    - name: Download 6th Attachment
      get_url:
        url: '{{ item.solatt06_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solatt06_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 6
      ignore_errors: True
          
#### 7th Attachment #####################################################################################
 
    - name: Insert 7th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.solatt07_FILE_NAME }}" target="_blank">{{ item.solatt07_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 7
      ignore_errors: True
  
    - name: Download 7th Attachment
      get_url:
        url: '{{ item.solatt07_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solatt07_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 7
      ignore_errors: True

#### 8th Attachment #####################################################################################

    - name: Insert 8th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.solatt08_FILE_NAME }}" target="_blank">{{ item.solatt08_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 8
      ignore_errors: True
  
    - name: Download 8th Attachment
      get_url:
        url: '{{ item.solatt08_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solatt08_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 8
      ignore_errors: True

#### 9th Attachment #####################################################################################
 
    - name: Insert 9th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.solatt09_FILE_NAME }}" target="_blank">{{ item.solatt09_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 9
      ignore_errors: True
  
    - name: Download 9th Attachment
      get_url:
        url: '{{ item.solatt09_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solatt09_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 9
      ignore_errors: True

#### 10th Attachment #####################################################################################

    - name: Insert 10th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="{{ item.solnumber }} attach">'
        line: '<a href="documents/{{ item.solnumber }}/{{ item.solatt10_FILE_NAME }}" target="_blank">{{ item.solatt10_FILE_NAME }}</a><br><br>'
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 10
      ignore_errors: True
  
    - name: Download 10th Attachment
      get_url:
        url: '{{ item.solatt10_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.solnumber }}/{{ item.solatt10_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 10
      ignore_errors: True

### Copy Files to FTP Server ###############################################################################
    
    - name: Copy Files to FTP
      command: ncftpput -R -u "{{ ftp_user_purch }}" -p "{{ ftp_pass_purch }}" "{{ ftp_url_purch }}" "{{ ftp_path_purch }}" "/{{ solicitation_doc_path }}/{{ item.solnumber }}"
      with_items: '{{ sol_vars.responses }}' 
      ignore_errors: True
  
    - name: Copy Index to FTP
      command: ncftpput -u "{{ ftp_user_purch }}" -p "{{ ftp_pass_purch }}" "{{ ftp_url_purch }}" /solicitations "{{ solicitation_html_path }}"
      ignore_errors: True
  
### Slack Notifications ####################################################################################
  
    - name: Notify Slack of Solicitation Posting
      slack:
        token: '{{ slack_token }}'
        msg: The Solicitation number '{{ item.solnumber }}' titled '{{ item.soltitle }}'  for '{{ item.solbuyer }}' has been posted.
      with_items: "{{ sol_vars.responses }}"
      when: modified

    
