---

- hosts: all
  become: true

  vars_files:
  - my_vars.yml

  tasks:

    - name: Delete Old Response Zip
      file:
        path: "sol.zip"
        state: absent
  
    - name: Delete Old Response File
      file:
        path: "Solicitations.json"
        state: absent

    - name: Register Current Hour as End Time
      set_fact:
        end_time: "{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
   
    - name: Munge Epoch Time Minus 11 Minutes for Start Time
      set_fact:
        start_time: "{{ '%H:%M' | strftime( ( ansible_date_time.epoch | int ) - ( 60 * 30 )  ) }}"

    - name: Register Current Date
      set_fact:
        date: "{{ ansible_date_time.date }}"

    - name: Create Qualtrics Response Export
      shell: |
        curl -X POST -H 'X-API-TOKEN: {{ sol_api_token }}' -H 'Content-Type: application/json' -d '{ 
        "surveyId": "{{ sol_survey_id }}",
        "format": "json",
        "startDate": "{{ date }}T{{ start_time }}:00-05:00",
        "endDate": "{{ date }}T{{ end_time }}:00-05:00",
        "useLabels": true
        }' 'https://ousurvey.qualtrics.com/API/v3/responseexports'
      register: sol_export

    - name: Register Qualtrics Request ID
      set_fact:
        sol_request_id: '{{ (sol_export.stdout | from_json).result.id }}'

    - name: Check Status of Qualtrics Response Export
      shell: |
        curl -H 'X-API-TOKEN: {{ sol_api_token }}' 'https://ousurvey.qualtrics.com/API/v3/responseexports/{{ sol_request_id }}'
      register: sol_progress

    - name: Download Qualtrics Response Export
      shell: |
        curl -X GET -H "Content-Type: application/json" -H "X-API-TOKEN: {{ sol_api_token }}" "https://ousurvey.qualtrics.com/API/v3/responseexports/{{ sol_request_id }}/file" -o sol.zip
      ignore_errors: True

    - name: Unzip Response File
      unarchive:
        src: sol.zip
        dest: .
      ignore_errors: True

    - name: Import JSON as Variables
      set_fact:      
        sol_vars: "{{ lookup('file','Solicitations.json') | from_json }}"
      ignore_errors: True
  
    - name: Modify Solicitation HTML
      blockinfile:
        path: '{{ solicitation_html_path }}'
        marker: "<!-- {mark} {{ item.Q8 }} {{ item.Q9 }} {{ item.Q2 }}-->"
        content: |
          <tr id="data">
            <td id="data"><span id="title"><b><u>{{ item.Q2 }}</u></b><br><br>{{ item.Q3 }}<span><br><br></td>
            <td id="data">{{ item.Q4 }}</td>
            <td id="data">{{ item.Q5 }}<br> email: <a href="mailto:{{ item.Q6 }}">{{ item.Q6 }}</a></td>
            <td id="data">{{ item.Q7 }}</td>
            <td id="data">{{ item.Q8 }} at {{ item.Q9 }} CT</td>
            <td id="data">[ <a href="documents/{{ item.Q2 }}/{{ item.Q10_FILE_NAME }}" target="_blank">{{ item.Q2 }}</a> ]<br><br></td>
            <td id="{{ item.Q2 }} attach">
            </td>
          </tr>
        state: present
        backup: yes
        insertbefore: "end solicitations"
      with_items: '{{ sol_vars.responses }}'
      register: modified
      when: sol_vars.responses != ""
  
    - name: Create Solicitation Directories
      file:
        path: '{{ solicitation_doc_path }}/{{ item.Q2 }}'
        state: directory
        mode: '0755'
      with_items: '{{ sol_vars.responses }}'
  
    - name: Download Solicitation Files
      get_url:
        url: '{{ item.Q10_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q10_FILE_NAME }}'
      when: item.Q10_FILE_NAME
      with_items: '{{ sol_vars.responses }}'
      ignore_errors: True
  
    - name: Check to see if there are Attachments
      set_fact:
        attachments: '{{ item.Q13 }}'
      with_items: '{{ sol_vars.responses }}'
  
    - name: Check to see number of Attachments
      set_fact:
        attachment_count: '{{ item.Q14 }}'
      with_items: '{{ sol_vars.responses }}'
  
    - name: Insert 1st Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q15_FILE_NAME }}" target="_blank">{{ item.Q15_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 1
      ignore_errors: True
  
    - name: Download 1st Attachment
      get_url:
        url: '{{ item.Q15_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q15_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 1
      ignore_errors: True
  
    - name: Insert 2nd Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q16_FILE_NAME }}" target="_blank">{{ item.Q16_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 2
      ignore_errors: True
  
    - name: Download 2nd Attachment
      get_url:
        url: '{{ item.Q16_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q16_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 2
      ignore_errors: True
  
    - name: Insert 3rd Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q17_FILE_NAME }}" target="_blank">{{ item.Q17_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 3
      ignore_errors: True
  
    - name: Download 3rd Attachment
      get_url:
        url: '{{ item.Q17_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q17_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 3
      ignore_errors: True
  
    - name: Insert 4th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q18_FILE_NAME }}" target="_blank">{{ item.Q18_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 4
      ignore_errors: True
  
    - name: Download 4th Attachment
      get_url:
        url: '{{ item.Q18_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q18_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 4
      ignore_errors: True
  
    - name: Insert 5th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q19_FILE_NAME }}" target="_blank">{{ item.Q19_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 5
      ignore_errors: True
  
    - name: Download 5th Attachment
      get_url:
        url: '{{ item.Q19_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q19_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 5
      ignore_errors: True
  
    - name: Insert 6th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q20_FILE_NAME }}" target="_blank">{{ item.Q20_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 6
      ignore_errors: True
  
    - name: Download 6th Attachment
      get_url:
        url: '{{ item.Q20_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q20_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 6
      ignore_errors: True
  
    - name: Insert 7th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q21_FILE_NAME }}" target="_blank">{{ item.Q21_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 7
      ignore_errors: True
  
    - name: Download 7th Attachment
      get_url:
        url: '{{ item.Q21_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q21_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 7
      ignore_errors: True
  
    - name: Insert 8th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q22_FILE_NAME }}" target="_blank">{{ item.Q22_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 8
      ignore_errors: True
  
    - name: Download 8th Attachment
      get_url:
        url: '{{ item.Q22_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q22_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 8
      ignore_errors: True
  
    - name: Insert 9th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q23_FILE_NAME }}" target="_blank">{{ item.Q23_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 9
      ignore_errors: True
  
    - name: Download 9th Attachment
      get_url:
        url: '{{ item.Q23_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q23_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 9
      ignore_errors: True
  
    - name: Insert 10th Attachment
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q24_FILE_NAME }}" target="_blank">{{ item.Q24_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 10
      ignore_errors: True
  
    - name: Download 10th Attachment
      get_url:
        url: '{{ item.Q24_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q24_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: attachment_count | int >= 10
      ignore_errors: True
  
    - name: Check to see if there is an Addendum
      set_fact:
        addendum: '{{ item.Q11 }}'
      with_items: '{{ sol_vars.responses }}'
  
    - name: Insert Addendum
      lineinfile:
        path: '{{ solicitation_html_path }}'
        insertafter: '<td id="attach">'
        line: '<a href="documents/{{ item.Q2 }}/{{ item.Q12_FILE_NAME }}" target="_blank">{{ item.Q12_FILE_NAME }}</a><br><br>'
        backup: yes
      with_items: '{{ sol_vars.responses }}'
      when: addendum
      ignore_errors: True
  
    - name: Download Addendum
      get_url:
        url: '{{ item.Q12_FILE_ID }}'
        dest: '{{ solicitation_doc_path }}/{{ item.Q2 }}/{{ item.Q12_FILE_NAME }}' 
      with_items: '{{ sol_vars.responses }}'
      when: addendum
  
    - name: Copy Files to FTP
      command: ncftpput -R -u "{{ ftp_user_purch }}" -p "{{ ftp_pass_purch }}" "{{ ftp_url_purch }}" "{{ ftp_path_purch }}" "/{{ solicitation_doc_path }}/{{ item.Q2 }}"
      with_items: '{{ sol_vars.responses }}' 
      ignore_errors: True
  
    - name: Copy Index to FTP
      command: ncftpput -u "{{ ftp_user_purch }}" -p "{{ ftp_pass_purch }}" "{{ ftp_url_purch }}" /solicitations "{{ solicitation_html_path }}"
      ignore_errors: True
  
    - name: Notify Slack of Posting Completion
      slack:
        token: '{{ slack_token }}'
        msg: The Solicitation number '{{ item.Q2 }}' titled '{{ item.Q3 }}'  for '{{ item.Q5 }}' has been posted.
      with_items: "{{ sol_vars.responses }}"
      when: modified
  
  
